<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>mo</string>
  </array>

  <key>name</key>
  <string>MetaModelica</string>

  <key>patterns</key>
  <array>
    <dict>
      <key>match</key> <string>\b(matchcontinue|match|local|case|end matchcontinue|end match)\b</string>
      <key>name</key>  <string>keyword.control</string>
    </dict>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key> <string>keyword</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key> <string>entity.name.type</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key> <string>string.quoted.double</string>
        </dict>
      </dict>
      <key>match</key> <string>\b(uniontype)\s+(\w+)\s*(".*")*</string>
    </dict>
    <dict>
      <key>begin</key> <string>\b(list\<|Option\<)\b</string>
      <key>end</key>   <string>></string>
      <key>name</key>  <string>storage.type</string>
    </dict>
    <dict>
      <key>include</key>
      <string>source.modelica</string>
    </dict>
  </array>

  <key>scopeName</key> <string>source.metamodelica</string>
  <key>uuid</key>      <string>44f94dc5-4fc2-49be-8d5b-d99966451a6d</string>
</dict>
</plist>
