name: CI
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup npm
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Translate grammar to JSON
        run: npm run prebuild

      - name: Archive tmGrammar files
        uses: actions/upload-artifact@v4
        with:
          name: tmGrammar.json
          path: syntaxes/*.tmGrammar.json

      - name: Build Package
        if: always()
        run: npm run build

      - name: Archive vsix package
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: metamodelica.vsix
          path: metamodelica-*.vsix

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup npm
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Download tmGrammar files
        uses: actions/download-artifact@v4
        with:
          name: tmGrammar.json

      - name: Run Test
        run: npm run test

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: metamodelica.vsix

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            metamodelica-*.vsix
          fail_on_unmatched_files: true
          generate_release_notes: true
          append_body: true
