name: Create MetaModelica VS Code Extension
on: 
  push:
    branches:
      - main
    tags:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Install the dependencies
        run: npm install
      - name: Build package
        run: npm run build
      - name: Archive vsix package
        uses: actions/upload-artifact@v3
        with:
          name: metamodelica.vsix
          path: metamodelica-*.vsix
